# Generated by Django 3.0 on 2022-01-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220119_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='apellido', max_length=255, verbose_name='Apellidos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='nombre', max_length=255, verbose_name='Nombres'),
            preserve_default=False,
        ),
    ]
