# Generated by Django 3.0 on 2022-01-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_name', models.CharField(max_length=50, verbose_name='Género')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=80, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('amount', models.FloatField(verbose_name='Monto')),
                ('status', models.BooleanField(verbose_name='Estado')),
                ('state', models.BooleanField(default=True, verbose_name='Estado eliminación')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Gender', verbose_name='Género')),
            ],
        ),
    ]
