# Generated by Django 3.0 on 2022-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Estado'),
        ),
    ]
