# Generated by Django 3.0 on 2022-01-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20220108_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
