# Generated by Django 3.0 on 2022-01-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_auto_20220108_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['id'], 'verbose_name': 'Préstamo', 'verbose_name_plural': 'Préstamos'},
        ),
        migrations.RemoveField(
            model_name='loan',
            name='modified_date',
        ),
    ]
